### ISSUE TITLE
TypeError in get_source_by_name

### ISSUE THREAD

**Issue by eSoares** [mk-fg/python-pulse-control#23]
When trying to obtain a source by it's name the following exception is thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/esoares/.local/lib/python3.6/site-packages/pulsectl/pulsectl.py", line 511, in _decorator_or_method
    return _wrapper(func_or_self, index)
  File "/home/esoares/.local/lib/python3.6/site-packages/pulsectl/pulsectl.py", line 498, in _wrapper
    pulse_func(self._ctx, *([index, cb, None] if index is not None else [cb, None]))
  File "/home/esoares/.local/lib/python3.6/site-packages/pulsectl/_pulsectl.py", line 605, in _wrapper
    res = func(*args)
ctypes.ArgumentError: argument 3: <class 'TypeError'>: expected CFunctionType instance instead of CFunctionType
```

Sample code:
```python
import pulsectl
a = pulsectl.Pulse("my_client")
a.get_source_by_name(a.sink_list()[0].name)
```

**Comment by mk-fg** [comment]
Hi,

Apparently had PA_SINK_INFO_CB_T copy-pasted there from get_sink_by_name instead of PA_SOURCE_INFO_CB_T, and no test to catch it.
Fixed both, should work fine now.

Thanks for reporting!
