### ISSUE TITLE
All unit tests and examples fail

### ISSUE THREAD

**Issue by rwilhelm** [mk-fg/python-pulse-control#30]
Hello!

The unit tests fail both using python2 and python3. The examples given in the readme fail at `pulse.volume_set(sink_input, new_volume)` with `pulsectl.pulsectl.PulseOperationFailed: 1`. Let me know if I can provide you with any other information.

```
4.14.83-gentoo x86_64 GNU/Linux
```
```
pulseaudio 12.2
pulsectl (18.12.5)
```

`python3 -m unittest pulsectl.tests.all`
```
EEE
======================================================================
ERROR: setUpClass (pulsectl.tests.dummy_instance.DummyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 146, in setUpClass
    cls.instance_info = dummy_pulse_init()
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 25, in dummy_pulse_init
    try: _dummy_pulse_init(info)
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 60, in _dummy_pulse_init
    s.bind((addr, p))
OSError: [Errno 99] Cannot assign requested address

======================================================================
ERROR: test_crash_after_connect (pulsectl.tests.dummy_instance.PulseCrashTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 473, in test_crash_after_connect
    info = dummy_pulse_init()
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 25, in dummy_pulse_init
    try: _dummy_pulse_init(info)
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 60, in _dummy_pulse_init
    s.bind((addr, p))
OSError: [Errno 99] Cannot assign requested address

======================================================================
ERROR: test_reconnect (pulsectl.tests.dummy_instance.PulseCrashTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 485, in test_reconnect
    info = dummy_pulse_init()
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 25, in dummy_pulse_init
    try: _dummy_pulse_init(info)
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 60, in _dummy_pulse_init
    s.bind((addr, p))
OSError: [Errno 99] Cannot assign requested address

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=3)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/asdf/local/src/github.com/mk-fg/python-pulse-control/pulsectl/tests/dummy_instance.py", line 151, in tearDownClass
    dummy_pulse_cleanup(cls.instance_info)
AttributeError: type object 'DummyTests' has no attribute 'instance_info'
```

Thanks

**Comment by mk-fg** [comment]
I see two separate issues here, though maybe related:

First one - all tests fail with `OSError: [Errno 99] Cannot assign requested address`.

Tests there are ran against dummy pulseaudio instance, which is bound to localhost IP address, and to do that, first python looks up any free port via that `s.bind((addr, p))` line, which fails with `OSError: [Errno 99] Cannot assign requested address`.
Tests with tcp connectivity are not isolated there, and yeah, whole fixture will fail if pulseaudio cannot start with tcp sockets.

I'd guess that you're either running that command from portage/paludis build sandbox which prohibits any networking, including such localhost binding, or have hardened system to the same effect.

Fix can be either allowing that connectivity [1], changing tests to not use it [2], or not running the tests in that sandbox [3].
Don't want to complicate test code for that one particular exceptional case, so probably won't do [2], but two other options should be open.

**Comment by mk-fg** [comment]
Second one:

> The examples given in the readme fail at `pulse.volume_set(sink_input, new_volume)` with `pulsectl.pulsectl.PulseOperationFailed: 1`

This suggests that libpulse was able to connect to pulseaudio instance, but something in the protocol fails after that.

I'd suggest running pulse daemon in verbose mode with -v option, e.g. via `pulseaudio -v`, and checking if it has anything to say about version or protocol mismatch for that connection and command.

If not, run that script with strace tool and see if maybe some network-related syscalls fail, as that seem to also happen with bind() above, even though connect() does't seem to fail here, but maybe send() does, which would cause such errors.

And if either one looks fine, it might just be the case that e.g. sink_input there refers to non-existing stream or volume passed is bogus in some way, which guess you can double-check.

Iirc libpulse doesn't return more descriptive errors, hence suggestions above.
I'd suspect it's most likely same weird OS/sandbox/LSM/container restrictions as you have with tests.
Though in this case you have libpulse returning error, and you might have to debug that (if everything above fails) to find what exactly is causing it, i.e. using gdb or something like that.
